[custom]

;设置规则标志位
ruleset=🕊️ 推特内容,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=📺 油管内容,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🍝 豆瓣内容,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouBan/DouBan.list
ruleset=🧣 围脖内容,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Weibo/Weibo.list
ruleset=🍠 红薯内容,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoHongShu/XiaoHongShu.list
ruleset=🎉 噼里啪啦,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
ruleset=🎉 噼里啪啦,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
ruleset=📻 网飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎵 字节跳动,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎵 字节跳动,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.list
ruleset=🎵 字节跳动,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KuaiShou/KuaiShou.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/1-JapanMedia.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/1-JapanStream.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TVer/TVer.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.list
ruleset=🌈 霓虹媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HuluJP/HuluJP.list
ruleset=🍰 鹿港媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=🍰 鹿港媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/KKTV/KKTV.list
ruleset=🥐 湾仔媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOHK/HBOHK.list
ruleset=🥐 湾仔媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TVB/TVB.list
ruleset=🥐 湾仔媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ViuTV/ViuTV.list
ruleset=🌎 漂亮媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ParamountPlus/ParamountPlus.list
ruleset=🌎 漂亮媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.list
ruleset=🌎 漂亮媒体,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/3-AmericaMaterial.list
ruleset=🌍 呆梨媒体,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/5-ItalySites.list
ruleset=🌍 呆梨媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DAZN/DAZN.list
ruleset=🌍 发髻媒体,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/6-FranceSites.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/2-ChinaMusic.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Youku/Youku.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TencentVideo/TencentVideo.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYI/iQIYI.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Himalaya/Himalaya.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LeTV/LeTV.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Migu/Migu.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PPTV/PPTV.list
ruleset=🌏 天朝媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/CCTV/CCTV.list
ruleset=📌 节点选择,https://raw.githubusercontent.com/sheisloveyeah/Rules4Freedom/Clash/rules/4-SelectiveSites.list
ruleset=❌ 垃圾拒绝,https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomo.yaml
ruleset=🎯 全球直连,[]GEOIP,GB
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🎁 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=👋 手动切换`select`.*
custom_proxy_group=📌 节点选择`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🕊️ 推特内容`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=📺 油管内容`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🍝 豆瓣内容`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🧣 围脖内容`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🍠 红薯内容`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🎉 噼里啪啦`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=📻 网飞视频`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🎵 字节跳动`select`[]DIRECT`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🌈 霓虹媒体`select`[]DIRECT`[]🇯🇵 日本节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🍰 鹿港媒体`select`[]DIRECT`[]🇹🇼 台湾节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🥐 湾仔媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🌎 漂亮媒体`select`[]DIRECT`[]🇺🇲 美国节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🌍 呆梨媒体`select`[]DIRECT`[]🇮🇹 意大利节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🌍 发髻媒体`select`[]DIRECT`[]🇫🇷 法兰西节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=🌏 天朝媒体`select`[]DIRECT`[]🇨🇳 中国节点`[]🎁 自动选择`[]👋 手动切换
custom_proxy_group=❌ 垃圾拒绝`select`[]DIRECT`[]REJECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🎁 自动选择`[]👋 手动切换`[]📌 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🎁 自动选择`[]👋 手动切换`[]📌 节点选择
custom_proxy_group=🇹🇼 台湾节点`url-test`(台湾|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(香港|Hong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(韩国|Korea)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美国|America)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇹 意大利节点`url-test`(意大利|Italy|Vantican)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇫🇷 法兰西节点`url-test`(法国|France|Nigeria)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 中国节点`url-test`(日志记录)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
